### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by bluesea2017** [gerstung-lab/MutationTimeR#2]
Hi,
  Can you give me two example files
vcf <- readVcf("myvcf.vcf") # Point mutations, needs info columns t_alt_count t_ref_count
bb <- GRanges(, major_cn= , minor_cn=, clonal_frequency=purity) # Copy number segments, needs columns  major_cn, minor_cn and clonal_frequency of each segment
 Thanks!

**Comment by sbamin** [comment]
Agree and would be of much help to try out this package.

Thanks

**Comment by mg14** [comment]
Should now be included
```
> data(MutationTimeR)
```

Also see
```
> example(mutationTime)
```
