### ISSUE TITLE
clonal_frequency clarification

### ISSUE THREAD

**Issue by Sames-Jtudd** [gerstung-lab/MutationTimeR#5]
HI there , 
quick question when its says "clonal_frequency of each segment" in regards to the "bb" file used as input. This would suggest to me that means the proporation of tumour cells with a given copy in that segment. In Battenberg parlance the  "frac1_A" or "frac1_B", this would therefore not be the same for all segments.
However in the example (https://github.com/gerstung-lab/MutationTimeR/blob/master/man/MutationTimeR.Rd) the clonal freqnecy is set as 0.8 of all segments, suggesting that it is the purity of the tumour sample (aka in Battenberg parlance the cellularity). This would therefore be the same for each segment.

If you could clarify which one is the correct input Id be grateful. 
Many thanks 
Jamie

**Comment by mg14** [comment]
Hi Jamie
`clonal_frequency` is measured as cellular proportion, rather than cancer cell fraction. 
So for clonal segments found in all cancer cells: `clonal_frequency` = purity (or cellularity)
Perhaps confusingly named indeed.
Cheers
Moritz

**Comment by mg14** [comment]
Hi Jamie
`clonal_frequency` is measured as cellular proportion, rather than cancer cell fraction. 
So for clonal segments found in all cancer cells: `clonal_frequency` = purity (or cellularity)
Perhaps confusingly named indeed.
Cheers
Moritz

**Comment by Sames-Jtudd** [comment]
Thanks for the clarification

Jamie

**Comment by Chitanda-Satou** [comment]
> 
> 
> Hi Jamie
> `clonal_frequency` is measured as cellular proportion, rather than cancer cell fraction.
> So for clonal segments found in all cancer cells: `clonal_frequency` = purity (or cellularity)
> Perhaps confusingly named indeed.
> Cheers
> Moritz

Dear @mg14, thanks for the information. May I ask that, how to set the "clonal_frequency" for "**subclonal** segements?

**Comment by carladosanjos** [comment]
Dear Moritz,

Many thanks for the previous explanation.

Still, it is not clear to me how you ended up with the `clonal_frequency` in the template data and how it is related to `purity`. Purity/cellularity is measured as cellular proportion regarding a tumor sample, not a genome segment. I understand the concept that and subclonals must have proportion < purity, but the previous given definition that `clonal_frequency = purity (or cellularity)`, does not make much sense as it is not given for each segment. Also, regarding the template data provided, how come the `clonal_frequency` can be the same for segments with different `major_cn` and `minor_cn`.

I am trying to figure out where the `clonal_frequency` of segments come from. My question is how did you generated the `clonal_frequency` for each segment (as a data.frame), specially the subclonals? Is it the output of any software, such as ABSOLUTE, or did you estimated it based on cell prevalence or other variable for each segment?

Many thanks!

**Comment by mg14** [comment]
For a clonal copy number segment,`clonal_frequency` = `purity`. In the example provided all segments are clonal.

If there was a subclonal copy number segment (eg. from ABSOLUTE or Battenberg) one has two entries in the GRanges object with identical coordinates, but different `major_cn` and/or `minor_cn` as well as `clonal_frequency` values. The sum of the two `clonal_frequency` values for that region needs to equal `purity`. 

Please note that a priori it is not clear which of the two configurations is ancestral and which one the derived (ie more recent) state. Usually it would be natural to assume that the diploid state is ancestral, but it doesn't have to be as in the case of WGD. For point mutations one usually does not specify the ancestral state, as it is implicitly assumed to be that of the matched normal.

**Comment by shaghayeghsoudi** [comment]
Is there any example of how the CNV file should look like when there are sub clonal CNV segments?
