### ISSUE TITLE
What is the meaning of "CLS = NA"?

### ISSUE THREAD

**Issue by b-niu** [gerstung-lab/MutationTimeR#7]
Hello, may I ask about that when CLS = NA, what does this mean?

Does it mean "unclassified", or something else?

In one project, I found that in all the results of MutationTimerR, there is no "subclonal", but many "NA" values. Just like:

![图片](https://user-images.githubusercontent.com/32410912/84632111-0754c900-af21-11ea-9326-d5c8d159f624.png)

![图片](https://user-images.githubusercontent.com/32410912/84632263-39fec180-af21-11ea-85d7-f6bf36e3dbb6.png)

**Comment by mg14** [comment]
`CLS = NA` arises when a point mutation cannot be timed. This usually occurs if either no information about the supporting read counts exists, or because copy number data is missing for the location of the variant.

HTH, 
Moritz
