### ISSUE TITLE
readVcf # Point mutations, needs `info` columns t_alt_count t_ref_count

### ISSUE THREAD

**Issue by carladosanjos** [gerstung-lab/MutationTimeR#8]
Dear author,

In some vcf files (GATK Funcotator output) , the **t_alt_count** and **t_ref_count** cannot be found as "INFO" column, but as "AD" FORMAT column (listed in "geno(vcf)"). Is there a way to make the MutationTimeR read the AD tag in the FORMAT field of the VCF file instead of searching for the  "t_alt_count" and  "t_ref_count" in the INFO field?

Many thanks!

**Comment by mg14** [comment]
Hi Carla

Can you check whether the above pull request works for you?

Thanks

Moritz
