### ISSUE TITLE
plotSample error

### ISSUE THREAD

**Issue by carladosanjos** [gerstung-lab/MutationTimeR#9]
Dear author,

I successfully ran the `mutationTime(vcf,bb,clusters,n.boot=10)` and got `timing_param` estimations and `CLS` summary but when I try to plot it using the `plotSample` I get following error:

`Error in contrasts<-(*tmp*, value = contr.funs[1 + isOF[nn]]) : contrasts can be applied only to factors with 2 or more levels`

Any cue what does it mean?

Here below you have some details regarding mutationTime output, so you might be able to see if there is something odd that prevents me to run the `plotSample`:

`mt$V
DataFrame with 1123 rows and 15 columns
         MutCN MutDeltaCN     MajCN     MinCN  MajDerCN  MinDerCN
     <numeric>  <numeric> <numeric> <numeric> <numeric> <numeric>
1            1          0         2         2         2         2
2            2          0         2         2         2         2
3            2          0         2         2         2         2
4            1          0         2         2         2         2
5            1          0         2         2         2         2
...        ...        ...       ...       ...       ...       ...
1119         2          0         2         1         2         1
1120         1          0         2         1         2         1
1121         2          0         2         1         2         1
1122         1          0         1         1         1         1
1123         1          0         1         1         1         1
                   CNF          CNID            pMutCN                pGain
             <numeric> <IntegerList>         <numeric>            <numeric>
1          0.000687318             2 0.494723343080384 5.76424135595753e-06
2    0.879098624695642             2 0.989599767309463    0.989599767309463
3    0.879098624695642             2 0.999992988099412    0.999992988099412
4          0.000687318             2 0.494723343080384 5.76424135595753e-06
5          0.000687318             2 0.483151830881478     0.02339549440017
...                ...           ...               ...                  ...
1119 0.576541244491539           297 0.762833583173009    0.762833583173009
1120       0.000687318           297 0.495454840676194 1.24579942305109e-05
1121 0.576541244491539           297 0.914657100525958    0.914657100525958
1122 0.686571870614507           298 0.481491329628669                    0
1123 0.686571870614507           298 0.481491329628669                    0
                   pSingle                 pSub pAllSubclones        pMutCNTail
                 <numeric>            <numeric>        <List>         <numeric>
1     5.24177869078851e-17    0.999994235758644                               1
2                        0    0.010400232690537               0.999999999718164
3    -1.11022302462516e-16 7.01190058768207e-06               0.999995222764883
4     5.24177869078851e-17    0.999994235758644                               1
5     4.85722573273506e-17     0.97660450559983                               1
...                    ...                  ...           ...               ...
1119                     0    0.237166416826991               0.861177068795532
1120 -6.94211262910679e-17     0.99998754200577               0.999302203699715
1121  1.11022302462516e-16   0.0853428994740418                0.76161834419779
1122     0.481491329628669    0.518508670371331               0.893693524471894
1123     0.481491329628669    0.518508670371331               0.893693524471894
                CLS
           <factor>
1         subclonal
2    clonal [early]
3    clonal [early]
4         subclonal
5         subclonal
...             ...
1119 clonal [early]
1120      subclonal
1121 clonal [early]
1122      subclonal
1123      subclonal

mt$T
DataFrame with 298 rows and 10 columns
                                                                            timing_param
                                                                                  <List>
1   1:1:0.234007956302873:...,1:2:0.468015912605745:...,2:1:0.000301573962029503:...,...
2   1:1:0.234027236750707:...,1:2:0.468054473501414:...,2:1:0.000301210376164352:...,...
3      1:1:0.119836773536088:...,1:2:0.239673547072177:...,1:3:0.359510320608265:...,...
4      1:1:0.296638793920009:...,1:2:0.593277587840019:...,2:1:0.403639933546563:...,...
5   1:1:0.234027720068522:...,1:2:0.468055440137045:...,2:1:0.000301201261877823:...,...
...                                                                                  ...
294    1:1:0.159406076648724:...,1:2:0.318812153297448:...,1:3:0.478218229946172:...,...
295     1:1:0.341368335878955:...,1:2:0.682736671757911:...,2:1:1.16329887022099:...,...
296     1:1:0.185200933790587:...,1:2:0.370401867581174:...,1:3:0.55560280137176:...,...
297    1:1:0.292716438522226:...,1:2:0.585432877044451:...,2:1:0.446785842922186:...,...
298 1:1:0.425611092841252:...,2:1:0.545518652497483:...,3:1:0.000701403706986437:...,...
                     type              time           time.lo           time.up
                 <factor>         <numeric>         <numeric>         <numeric>
1   Bi-allelic Gain (WGD)                NA                NA                NA
2   Bi-allelic Gain (WGD)                 1 0.666666666666667                 1
3                      NA                NA                NA                NA
4       Mono-allelic Gain                NA                NA                NA
5   Bi-allelic Gain (WGD)                 1             0.375                 1
...                   ...               ...               ...               ...
294 Bi-allelic Gain (WGD) 0.500124474223747 0.272756598967361 0.727356023556023
295                CN-LOH                NA                NA                NA
296 Bi-allelic Gain (WGD)                 1 0.782608695652174                 1
297     Mono-allelic Gain                 1 0.666666666666667                 1
298                    NA                NA                NA                NA
             time.2nd       time.2nd.lo       time.2nd.up time.star n.snv_mnv
            <numeric>         <numeric>         <numeric>  <factor> <integer>
1                  NA                NA                NA        NA         0
2                  NA                NA                NA       ***        10
3                  NA                NA                NA        NA         0
4                  NA                NA                NA        NA         0
5                  NA                NA                NA       ***         3
...               ...               ...               ...       ...       ...
294 0.999744738201372 0.545276742955156 0.999939608061335        **         6
295                NA                NA                NA        NA         0
296                 1 0.782608695652174                 1        **        18
297                NA                NA                NA       ***        10
298                NA                NA                NA        NA         2
`

Many thanks for your help!

Best wishes,

Carla

**Comment by mg14** [comment]
Hi Carla

Not sure what the issue is -- the intermediate output looks OK. Have you added it to the `vcf` and `cn` (`bb`) files?

Let me know if the issue is persistent and I will reopend.

M

**Comment by lydiayliu** [comment]
I also ran into this issue and I wanted to follow up on just in case anybody runs into this issue in the future.

I believe the issue is with these lines in the plotting function
https://github.com/gerstung-lab/MutationTimeR/blob/e4e266a494482face03e831322a9df00b1b0ff93/R/MutationTime.R#L1001-L1010

If no `regions` is given as params, the default `refLengths` is used.
```
> MutationTimeR:::refLengths[1:23]GRanges object with 23 ranges and 0 metadata columns:
       seqnames      ranges strand
          <Rle>   <IRanges>  <Rle>
   [1]        1 1-249250621      *
   [2]        2 1-243199373      *
   [3]        3 1-198022430      *
   [4]        4 1-191154276      *
   [5]        5 1-180915260      *
   ...      ...         ...    ...
  [19]       19  1-59128983      *
  [20]       20  1-63025520      *
  [21]       21  1-48129895      *
  [22]       22  1-51304566      *
  [23]        X 1-155270560      *
  -------
  seqinfo: 86 sequences from an unspecified genome
```

But `bbb <- cn[cn %over% regions]` would cause the following warning IF your cna data has `chr` in seqnames, resulting in no overlaping seqlevels.
```
1: In .Seqinfo.mergexy(x, y) :                                                                                                                                           
  The 2 combined objects have no sequence levels in common. (Use                                                                                                         
  suppressWarnings() to suppress this warning.)  
```

I managed to fix the issue after removing `chr` from `seqnames` of my vcf and cna data.

The other note is that the default regions used is the hs37d5 genome build, I used my own regions GRanges object for GRCh38. It must also not have `chr`. Even if all objects have `chr` something still breaks.
